apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs
  spec:
    containers:
      - name: udacity
    image: akwele/capstone
    ports:
      - containerPort: 3000
