apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  progressDeadlineSeconds: 1200
  minReadySeconds: 60
  template:
    metadata:
      labels:
        app: capstone
    spec:
      terminationGracePeriodSeconds: 60
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - capstone
                  - key: "temporary"
                    operator: In
                    values:
                      - "true"
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: udacity
          image: akwele/capstone
          command: ["npm", "run", "dev"]
          imagePullPolicy: Always
          resources:
            limits:
              memory: 64Mi
              cpu: 250m
            requests:
              memory: 32Mi
              cpu: 200m
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              scheme: HTTP
              port: 80
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
