version: '3.1'

services:

  mongo:
    image: mongo:3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - "27017"
    ports:
      - "27017:27017"

  frontend:
    build: ./frontend/
    expose:
      - "4100"
    ports:
      - "4100:4100"


  backend:
    depends_on:
      - mongo
    build: ./backend/
    environment:
      - MONGODB_URI=mongodb://mongo/conduit
    expose:
      - "3000"
