---
- hosts: host
  become: true
  pre_tasks:
    - name: install updates
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Set up Amazon EKS
  roles:
    - eks
